CREATE DATABASE FINALASS_FPOLYSHOP_FA22_SOF205__SOF2041
go
USE FINALASS_FPOLYSHOP_FA22_SOF205__SOF2041
GO
-- ChucVu
CREATE TABLE chuc_vu(
id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
ma VARCHAR(20) UNIQUE,
ten NVARCHAR(50) DEFAULT NULL
)
GO
-- CuaHang
CREATE TABLE cua_hang(
id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
ma VARCHAR(20) UNIQUE,
ten NVARCHAR(50) DEFAULT NULL,
dia_chi NVARCHAR(100) DEFAULT NULL,
thanh_pho NVARCHAR(50) DEFAULT NULL,
quoc_gia NVARCHAR(50) DEFAULT NULL
)
GO
-- NhanVien
CREATE TABLE nhan_vien(
id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
ma VARCHAR(20) UNIQUE,
ho NVARCHAR(30) DEFAULT NULL,
ten_dem NVARCHAR(30) DEFAULT NULL,
ten NVARCHAR(30) DEFAULT NULL,
gioi_tinh INT DEFAULT 0,
ngay_sinh DATE DEFAULT NULL,
dia_chi NVARCHAR(100) DEFAULT NULL,
sdt VARCHAR(30) DEFAULT NULL,
mat_khau VARCHAR(MAX) DEFAULT NULL,
trang_thai INT DEFAULT 0,
id_ch UNIQUEIDENTIFIER,
id_cv UNIQUEIDENTIFIER,
id_guibc UNIQUEIDENTIFIER
)
GO
-- KhachHang
CREATE TABLE khach_hang(
id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
ma VARCHAR(20) UNIQUE,
ho NVARCHAR(30) DEFAULT NULL,
ten_dem NVARCHAR(30) DEFAULT NULL,
ten NVARCHAR(30) DEFAULT NULL,
ngay_sinh DATE DEFAULT NULL,
sdt VARCHAR(30) DEFAULT NULL,
dia_chi NVARCHAR(100) DEFAULT NULL,
thanh_pho NVARCHAR(50) DEFAULT NULL,
quoc_gia NVARCHAR(50) DEFAULT NULL,
mat_khau VARCHAR(MAX) DEFAULT NULL
)
GO
--HoaDon
CREATE TABLE hoa_don(
id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
id_kh UNIQUEIDENTIFIER,
id_nv UNIQUEIDENTIFIER,
ma VARCHAR(20) UNIQUE,
ngay_tao DATE DEFAULT NULL,
ngay_thanh_toan DATE DEFAULT NULL,
ngay_ship DATE DEFAULT NULL,
ngay_nhan DATE DEFAULT NULL,
tinh_trang INT DEFAULT 0,
ten_nguoi_nhan NVARCHAR(50) DEFAULT NULL,
dia_chi NVARCHAR(100) DEFAULT NULL,
sdt VARCHAR(30) DEFAULT NULL,
)
GO
CREATE TABLE gio_hang(
id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
id_kh UNIQUEIDENTIFIER,
id_nv UNIQUEIDENTIFIER,
ma VARCHAR(20) UNIQUE,
ngay_tao DATE DEFAULT NULL,
ngay_thanh_toan DATE DEFAULT NULL,
ten_nguoi_nhan NVARCHAR(50) DEFAULT NULL,
dia_chi NVARCHAR(100) DEFAULT NULL,
sdt VARCHAR(30) DEFAULT NULL,
tinh_trang INT DEFAULT 0
)
GO
-- SanPham
CREATE TABLE san_pham(
id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
ma VARCHAR(20) UNIQUE,
ten NVARCHAR(30)
)
GO
-- NSX
CREATE TABLE n_s_x(
id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
ma VARCHAR(20) UNIQUE,
ten NVARCHAR(30)
)
GO
-- MauSac
CREATE TABLE mau_sac(
id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
ma VARCHAR(20) UNIQUE,
ten NVARCHAR(30)
)
GO
-- DongSP
CREATE TABLE dong_sp(
id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
ma VARCHAR(20) UNIQUE,
ten NVARCHAR(30)
)
GO
-- ChiTietSP
CREATE TABLE chitiet_sp(
id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
id_sp UNIQUEIDENTIFIER,
id_nsx UNIQUEIDENTIFIER,
id_mausac UNIQUEIDENTIFIER,
id_dongsp UNIQUEIDENTIFIER,
nam_bh INT DEFAULT NULL,
mo_ta NVARCHAR(50) DEFAULT NULL,
so_luong_ton INT,
gia_nhap DECIMAL(20,0) DEFAULT 0,
gia_ban DECIMAL(20,0) DEFAULT 0,
)

GO
-- HoaDonChiTiet
CREATE TABLE hoadon_chitiet(
id_hoadon UNIQUEIDENTIFIER,
id_chitietsp UNIQUEIDENTIFIER,
so_luong INT,
don_gia DECIMAL(20,0) DEFAULT 0,
CONSTRAINT PK_HoaDonCT PRIMARY KEY (id_hoadon,id_chitietsp),
CONSTRAINT FK1 FOREIGN KEY(id_hoadon) REFERENCES hoa_don(Id),
CONSTRAINT FK2 FOREIGN KEY(id_chitietsp) REFERENCES ChiTiet_SP(Id),
)
GO
CREATE TABLE giohang_chitiet(
id_giohang UNIQUEIDENTIFIER,
id_chitietsp UNIQUEIDENTIFIER,
so_luong INT,
don_gia DECIMAL(20,0) DEFAULT 0,
don_gia_khi_giam DECIMAL(20,0) DEFAULT 0,
CONSTRAINT PK_GioHangCT PRIMARY KEY (id_giohang,id_chitietsp),
CONSTRAINT FK1_IdGioHang FOREIGN KEY(id_giohang) REFERENCES gio_hang(id),
CONSTRAINT FK2_IdChiTietSP FOREIGN KEY(id_chitietsp) REFERENCES chitiet_sp(id),
)
GO
--TẠO QUAN HỆ GIỮA CÁC BẢNG
--NhanVien - CuaHang
ALTER TABLE nhan_vien ADD FOREIGN KEY (id_ch) REFERENCES cua_hang(id)
--NhanVien - ChucVu
ALTER TABLE nhan_vien ADD FOREIGN KEY (id_cv) REFERENCES chuc_vu(id)
--NhanVien - GuiBaoCao
ALTER TABLE nhan_vien ADD FOREIGN KEY (id_guibc) REFERENCES nhan_vien(id)
-- HoaDon - KhachHang
ALTER TABLE hoa_don ADD FOREIGN KEY (id_kh) REFERENCES khach_hang(id)
-- GioHang - KhachHang
ALTER TABLE gio_hang ADD FOREIGN KEY (id_kh) REFERENCES khach_hang(id)
-- HoaDon - NhanVien
ALTER TABLE hoa_don ADD FOREIGN KEY (id_nv) REFERENCES nhan_vien(id)
-- ChiTietSP - SanPham
ALTER TABLE chitiet_sp ADD FOREIGN KEY(id_sp) REFERENCES san_pham(id)
-- ChiTietSP - NSX
ALTER TABLE chitiet_sp ADD FOREIGN KEY(id_nsx) REFERENCES n_s_x(id)
-- ChiTietSP - MauSac
ALTER TABLE chitiet_sp ADD FOREIGN KEY(id_mausac) REFERENCES mau_sac(id)
-- ChiTietSP - DongSP
ALTER TABLE chitiet_sp ADD FOREIGN KEY(id_dongsp) REFERENCES dong_sp(id)